services:
  server:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db/sh_rs
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sh_rs
    volumes:
      - db:/var/lib/postgresql

volumes:
  db: