services:
  server:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgres://user:password@db/sh_rs
      REDIS_URL: redis://redis
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sh_rs
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"