[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
time = { version = "0.3.41", features = ["formatting", "local-offset"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["time"] }
